# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46822f7dc4ee0ef46691e55f9b3a1538723a9094b8f1958227f35b2866c31f86d34d56bd1ebb88abada0dddba0505657ead66b00e49b43e810cbaf7212aee800

test:
  secret_key_base: 928195cbd4b43b97498d282a4edc3bfc628884f3e1818ce0f317863b0fd97ecaa3aa6ca7cc4f5bd9a9ef6b1b49bc3d578d6b8e12159295e55d8fc02a54b0d873

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
